use ColDB;
drop table OITM;
CREATE TABLE OITM (
    ItemCode NVARCHAR(50),
    ItemName NVARCHAR(100),
    FrgnName NVARCHAR(100),
    ItmsGrpCod INT,
    CstGrpCode INT,
    VatGourpSa NVARCHAR(20),
    CodeBars NVARCHAR(100),
    VATLiable CHAR(1),
    PrchseItem CHAR(1),
    SellItem CHAR(1),
    InvntItem CHAR(1),
    OnHand DECIMAL(19,6),
    IsCommited DECIMAL(19,6),
    OnOrder DECIMAL(19,6),
    IncomeAcct NVARCHAR(15),
    ExmptIncom NVARCHAR(15),
    MaxLevel DECIMAL(19,6),
    DfltWH NVARCHAR(8),
    CardCode NVARCHAR(15),
    SuppCatNum NVARCHAR(50),
    BuyUnitMsr NVARCHAR(20),
    NumInBuy DECIMAL(19,6),
    ReorderQty DECIMAL(19,6),
    MinLevel DECIMAL(19,6),
    LstEvlPric DECIMAL(19,6),
    LstEvlDate DATETIME,
    CustomPer DECIMAL(19,6),
    Canceled CHAR(1),
    MnufctTime INT,
    WholSlsTax NVARCHAR(15),
    RetilrTax NVARCHAR(15),
    SpcialDisc DECIMAL(19,6),
    DscountCod NVARCHAR(8),
    TrackSales CHAR(1),
    SalUnitMsr NVARCHAR(20),
    NumInSale DECIMAL(19,6),
    Consig CHAR(1),
    QueryGroup NVARCHAR(8),
    Counted CHAR(1),
    OpenBlnc DECIMAL(19,6),
    EvalSystem NVARCHAR(8),
    UserSign INT,
    FREE NVARCHAR(8),
    PicturName NVARCHAR(100),
    Transfered CHAR(1),
    BlncTrnsfr DECIMAL(19,6),
    UserText NVARCHAR(254),
    SerialNum NVARCHAR(100),
    CommisPcnt DECIMAL(19,6),
    CommisSum DECIMAL(19,6),
    CommisGrp NVARCHAR(8),
    TreeType NVARCHAR(8),
    TreeQty DECIMAL(19,6),
    LastPurPrc DECIMAL(19,6),
    LastPurCur NVARCHAR(3),
    LastPurDat DATETIME,
    ExitCur NVARCHAR(3),
    ExitPrice DECIMAL(19,6),
    ExitWH NVARCHAR(8),
    AssetItem CHAR(1),
    WasCounted CHAR(1),
    ManSerNum CHAR(1),
    SHeight1 DECIMAL(19,6),
    SHght1Unit NVARCHAR(8),
    SHeight2 DECIMAL(19,6),
    SHght2Unit NVARCHAR(8),
    SWidth1 DECIMAL(19,6),
    SWdth1Unit NVARCHAR(8),
    SWidth2 DECIMAL(19,6),
    SWdth2Unit NVARCHAR(8),
    SLength1 DECIMAL(19,6),
    SLen1Unit NVARCHAR(8),
    Slength2 DECIMAL(19,6),
    SLen2Unit NVARCHAR(8),
    SVolume DECIMAL(19,6),
    SVolUnit NVARCHAR(8),
    SWeight1 DECIMAL(19,6),
    SWght1Unit NVARCHAR(8),
    SWeight2 DECIMAL(19,6),
    SWght2Unit NVARCHAR(8),
    BHeight1 DECIMAL(19,6),
    BHght1Unit NVARCHAR(8),
    BHeight2 DECIMAL(19,6),
    BHght2Unit NVARCHAR(8),
    BWidth1 DECIMAL(19,6),
    BWdth1Unit NVARCHAR(8),
    BWidth2 DECIMAL(19,6),
    BWdth2Unit NVARCHAR(8),
    BLength1 DECIMAL(19,6),
    BLen1Unit NVARCHAR(8),
    Blength2 DECIMAL(19,6),
    BLen2Unit NVARCHAR(8),
    BVolume DECIMAL(19,6),
    BVolUnit NVARCHAR(8),
    BWeight1 DECIMAL(19,6),
    BWght1Unit NVARCHAR(8),
    BWeight2 DECIMAL(19,6),
    BWght2Unit NVARCHAR(8),
    FixCurrCms DECIMAL(19,6),
    FirmCode NVARCHAR(20),
    LstSalDate DATETIME,
    QryGroup1 CHAR(1),
    QryGroup2 CHAR(1),
    QryGroup3 CHAR(1),
    QryGroup4 CHAR(1),
    QryGroup5 CHAR(1),
    QryGroup6 CHAR(1),
    QryGroup7 CHAR(1),
    QryGroup8 CHAR(1),
    QryGroup9 CHAR(1),
    QryGroup10 CHAR(1),
    QryGroup11 CHAR(1),
    QryGroup12 CHAR(1),
    QryGroup13 CHAR(1),
    QryGroup14 CHAR(1),
    QryGroup15 CHAR(1),
    QryGroup16 CHAR(1),
    QryGroup17 CHAR(1),
    QryGroup18 CHAR(1),
    QryGroup19 CHAR(1),
    QryGroup20 CHAR(1),
    QryGroup21 CHAR(1),
    QryGroup22 CHAR(1),
    QryGroup23 CHAR(1),
    QryGroup24 CHAR(1),
    QryGroup25 CHAR(1),
    QryGroup26 CHAR(1),
    QryGroup27 CHAR(1),
    QryGroup28 CHAR(1),
    QryGroup29 CHAR(1),
    QryGroup30 CHAR(1),
    QryGroup31 CHAR(1),
    QryGroup32 CHAR(1),
    QryGroup33 CHAR(1),
    QryGroup34 CHAR(1),
    QryGroup35 CHAR(1),
    QryGroup36 CHAR(1),
    QryGroup37 CHAR(1),
    QryGroup38 CHAR(1),
    QryGroup39 CHAR(1),
    QryGroup40 CHAR(1),
    QryGroup41 CHAR(1),
    QryGroup42 CHAR(1),
    QryGroup43 CHAR(1),
    QryGroup44 CHAR(1),
    QryGroup45 CHAR(1),
    QryGroup46 CHAR(1),
    QryGroup47 CHAR(1),
    QryGroup48 CHAR(1),
    QryGroup49 CHAR(1),
    QryGroup50 CHAR(1),
    QryGroup51 CHAR(1),
    QryGroup52 CHAR(1),
    QryGroup53 CHAR(1),
    QryGroup54 CHAR(1),
    QryGroup55 CHAR(1),
    QryGroup56 CHAR(1),
    QryGroup57 CHAR(1),
    QryGroup58 CHAR(1),
    QryGroup59 CHAR(1),
    QryGroup60 CHAR(1),
    QryGroup61 CHAR(1),
    QryGroup62 CHAR(1),
    QryGroup63 CHAR(1),
    QryGroup64 CHAR(1),
    CreateDate DATETIME,
    UpdateDate DATETIME,
    ExportCode NVARCHAR(20),
    SalFactor1 DECIMAL(19,6),
    SalFactor2 DECIMAL(19,6),
    SalFactor3 DECIMAL(19,6),
    SalFactor4 DECIMAL(19,6),
    PurFactor1 DECIMAL(19,6),
    PurFactor2 DECIMAL(19,6),
    PurFactor3 DECIMAL(19,6),
    PurFactor4 DECIMAL(19,6),
    SalFormula NVARCHAR(50),
    PurFormula NVARCHAR(50),
    VatGroupPu NVARCHAR(20),
    AvgPrice DECIMAL(19,6),
    PurPackMsr NVARCHAR(20),
    PurPackUn DECIMAL(19,6),
    SalPackMsr NVARCHAR(20),
    SalPackUn DECIMAL(19,6),
    SCNCounter INT,
    ManBtchNum CHAR(1),
    ManOutOnly CHAR(1),
    DataSource NVARCHAR(10),
    validFor CHAR(1),
    validFrom DATETIME,
    validTo DATETIME,
    frozenFor CHAR(1),
    frozenFrom DATETIME,
    frozenTo DATETIME,
    BlockOut CHAR(1),
    ValidComm NVARCHAR(50),
    FrozenComm NVARCHAR(50),
    LogInstanc INT,
    ObjType NVARCHAR(20),
    SWW NVARCHAR(100),
    Deleted CHAR(1),
    DocEntry INT,
    ExpensAcct NVARCHAR(15),
    FrgnInAcct NVARCHAR(15),
    ShipType NVARCHAR(20),
    GLMethod NVARCHAR(20),
    ECInAcct NVARCHAR(15),
    FrgnExpAcc NVARCHAR(15),
    ECExpAcc NVARCHAR(15),
    TaxType NVARCHAR(10),
    ByWh CHAR(1),
    WTLiable CHAR(1),
    ItemType NVARCHAR(10),
    WarrntTmpl NVARCHAR(20),
    BaseUnit NVARCHAR(20),
    CountryOrg NVARCHAR(3),
    StockValue DECIMAL(19,6),
    Phantom CHAR(1),
    IssueMthd NVARCHAR(10),
    FREE1 NVARCHAR(20),
    PricingPrc DECIMAL(19,6),
    MngMethod NVARCHAR(10),
    ReorderPnt DECIMAL(19,6),
    InvntryUom NVARCHAR(20),
    PlaningSys NVARCHAR(10),
    PrcrmntMtd NVARCHAR(10),
    OrdrIntrvl DECIMAL(19,6),
    OrdrMulti DECIMAL(19,6),
    MinOrdrQty DECIMAL(19,6),
    LeadTime DECIMAL(19,6),
    IndirctTax NVARCHAR(20),
    TaxCodeAR NVARCHAR(20),
    TaxCodeAP NVARCHAR(20),
    OSvcCode NVARCHAR(20),
    ISvcCode NVARCHAR(20),
    ServiceGrp NVARCHAR(20),
    NCMCode NVARCHAR(20),
    MatType NVARCHAR(20),
    MatGrp NVARCHAR(20),
    ProductSrc NVARCHAR(20),
    ServiceCtg NVARCHAR(20),
    ItemClass NVARCHAR(20),
    Excisable CHAR(1),
    ChapterID NVARCHAR(20),
    NotifyASN CHAR(1),
    ProAssNum NVARCHAR(20),
    AssblValue DECIMAL(19,6),
    DNFEntry INT,
    UserSign2 INT,
    Spec NVARCHAR(100),
    TaxCtg NVARCHAR(20),
    Series INT,
    Number INT,
    FuelCode NVARCHAR(20),
    BeverTblC NVARCHAR(20),
    BeverGrpC NVARCHAR(20),
    BeverTM NVARCHAR(20),
    Attachment NVARCHAR(100),
    AtcEntry INT,
    ToleranDay DECIMAL(19,6),
    UgpEntry INT,
    PUoMEntry INT,
    SUoMEntry INT,
    IUoMEntry INT,
    IssuePriBy NVARCHAR(20),
    AssetClass NVARCHAR(20),
    AssetGroup NVARCHAR(20),
    InventryNo NVARCHAR(50),
    Technician NVARCHAR(50),
    Employee NVARCHAR(50),
    Location NVARCHAR(100),
    StatAsset CHAR(1),
    Cession CHAR(1),
    DeacAftUL CHAR(1),
    AsstStatus NVARCHAR(20),
    CapDate DATETIME,
    AcqDate DATETIME,
    RetDate DATETIME,
    GLPickMeth NVARCHAR(20),
    NoDiscount CHAR(1),
    MgrByQty CHAR(1),
    AssetRmk1 NVARCHAR(100),
    AssetRmk2 NVARCHAR(100),
    AssetAmnt1 DECIMAL(19,6),
    AssetAmnt2 DECIMAL(19,6),
    DeprGroup NVARCHAR(20),
    AssetSerNo NVARCHAR(50),
    CntUnitMsr NVARCHAR(20),
    NumInCnt DECIMAL(19,6),
    INUoMEntry INT,
    OneBOneRec CHAR(1),
    RuleCode NVARCHAR(20),
    ScsCode NVARCHAR(20),
    SpProdType NVARCHAR(20),
    IWeight1 DECIMAL(19,6),
    IWght1Unit NVARCHAR(8),
    IWeight2 DECIMAL(19,6),
    IWght2Unit NVARCHAR(8),
    CompoWH NVARCHAR(20),
    CreateTS DATETIME,
    UpdateTS DATETIME,
    VirtAstItm CHAR(1),
    SouVirAsst NVARCHAR(20),
    InCostRoll CHAR(1),
    PrdStdCst DECIMAL(19,6),
    EnAstSeri CHAR(1),
    LinkRsc NVARCHAR(20),
    OnHldPert DECIMAL(19,6),
    onHldLimt DECIMAL(19,6),
    PriceUnit DECIMAL(19,6),
    GSTRelevnt CHAR(1),
    SACEntry INT,
    GstTaxCtg NVARCHAR(20),
    AssVal4WTR DECIMAL(19,6),
    ExcImpQUoM DECIMAL(19,6),
    ExcFixAmnt DECIMAL(19,6),
    ExcRate DECIMAL(19,6),
    SOIExc NVARCHAR(20),
    TNVED NVARCHAR(20),
    Imported CHAR(1),
    AutoBatch CHAR(1),
    CstmActing NVARCHAR(20),
    StdItemId NVARCHAR(20),
    CommClass NVARCHAR(20),
    TaxCatCode NVARCHAR(20),
    DataVers NVARCHAR(20),
    NVECode NVARCHAR(20),
    CESTCode NVARCHAR(20),
    CtrSealQty DECIMAL(19,6),
    LegalText NVARCHAR(254),
    QRCodeSrc NVARCHAR(100),
    Traceable CHAR(1),
    IfrsPsRev NVARCHAR(20),
    PlPaTaxCat NVARCHAR(20),
    PlPaWght DECIMAL(19,6),
    PPTExReSa CHAR(1),
    PPTExRePr CHAR(1),
    ProdctType NVARCHAR(20),
    U_Colour NVARCHAR(50),
    U_Category NVARCHAR(50),
    U_SizeGrp NVARCHAR(50),
    U_Size NVARCHAR(50),
    U_Vendor NVARCHAR(50),
    U_ShelfLife DECIMAL(19,6),
    U_MinReOrdrQty DECIMAL(19,6),
    U_MinOrder DECIMAL(19,6),
    U_DisGrp NVARCHAR(50),
    U_Block NVARCHAR(50),
    U_ReItem NVARCHAR(50),
    U_SpItmReOdr NVARCHAR(50),
    U_StyleNo NVARCHAR(50),
    U_Product NVARCHAR(50),
    U_SubGrp NVARCHAR(50),
    U_StyGrp NVARCHAR(50),
    U_Cost DECIMAL(19,6),
    U_Material NVARCHAR(50),
    U_Sole NVARCHAR(50),
    U_Fashion NVARCHAR(50),
    U_TaxName NVARCHAR(50),
    U_MRP DECIMAL(19,6),
    U_Upper NVARCHAR(50),
    U_SoleBase NVARCHAR(50),
    U_LstShape NVARCHAR(50),
    U_Comfort NVARCHAR(50),
    U_Fitting NVARCHAR(50),
    U_Life NVARCHAR(50),
    U_Remarks NVARCHAR(100),
    U_SPrefix NVARCHAR(50),
    U_TaxType NVARCHAR(50),
    U_AccFrom NVARCHAR(50),
    U_AccTo NVARCHAR(50),
    U_PrimCode NVARCHAR(50),
    U_SecCode NVARCHAR(50),
    U_PrimRate DECIMAL(19,6),
    U_SecRate DECIMAL(19,6),
    U_Remarks2 NVARCHAR(100),
    U_Brand NVARCHAR(50),
    U_Gender NVARCHAR(50),
    U_ProdName NVARCHAR(50),
    U_ProdType NVARCHAR(50),
    U_Online CHAR(1),
    U_Height DECIMAL(19,6),
    U_HType NVARCHAR(50),
    U_Length DECIMAL(19,6),
    U_LType NVARCHAR(50),
    U_Width DECIMAL(19,6),
    U_WType NVARCHAR(50),
    U_UpdateTime DATETIME,
    U_ShipCost DECIMAL(19,6),
    U_Weight DECIMAL(19,6),
    U_Exchange CHAR(1),
    U_TryBuy CHAR(1),
    U_TryBuyAmt DECIMAL(19,6),
    U_ChartID NVARCHAR(50),
    U_SpeItem NVARCHAR(50),
    U_OnLineCat NVARCHAR(50),
    U_conceptno NVARCHAR(100)
);
select *from OITM;

SELECT COUNT(*) 
FROM INFORMATION_SCHEMA.COLUMNS 
WHERE TABLE_NAME = 'OITM';

INSERT INTO OITM (
    ItemCode, ItemName, FrgnName, ItmsGrpCod, CstGrpCode, VatGourpSa, CodeBars,
    VATLiable, PrchseItem, SellItem, InvntItem, OnHand, IsCommited, OnOrder,
    IncomeAcct, ExmptIncom, MaxLevel, DfltWH, CardCode, SuppCatNum,
    BuyUnitMsr, NumInBuy, ReorderQty, MinLevel, LstEvlPric, LstEvlDate,
    CustomPer, Canceled, MnufctTime, WholSlsTax, RetilrTax, SpcialDisc,
    DscountCod, TrackSales, SalUnitMsr, NumInSale, Consig, QueryGroup, Counted,
    OpenBlnc, EvalSystem, UserSign, FREE, PicturName, Transfered, BlncTrnsfr,
    UserText, SerialNum, CommisPcnt, CommisSum, CommisGrp, TreeType, TreeQty,
    LastPurPrc, LastPurCur, LastPurDat, ExitCur, ExitPrice, ExitWH, AssetItem,
    WasCounted, ManSerNum, SHeight1, SHght1Unit, SWidth1, SWdth1Unit,
    SLength1, SLen1Unit, SVolume, SVolUnit, SWeight1, SWght1Unit,
    BHeight1, BHght1Unit, BWidth1, BWdth1Unit, BLength1, BLen1Unit,
    BVolume, BVolUnit, BWeight1, BWght1Unit, FirmCode, LstSalDate,
    CreateDate, UpdateDate, ExportCode, SalFactor1, PurFactor1,
    VatGroupPu, AvgPrice, PurPackMsr, SalPackMsr, validFor, validFrom, validTo,
    BlockOut, ObjType, ItemType, BaseUnit, CountryOrg, StockValue,
    IssueMthd, InvntryUom, PlaningSys, PrcrmntMtd,
    U_Colour, U_Category, U_SizeGrp, U_Size, U_Vendor, U_DisGrp, U_Product,
    U_StyleNo, U_Brand, U_Gender, U_ProdName, U_ProdType, U_Material, U_Sole,
    U_MRP, U_Remarks, U_UpdateTime
) VALUES (
    'SH001',                               
    N'Men Running Shoes',                  
    N'Schuhe Herren',                      
    101,                                  
    1,                                    
    'VAT18',                               
    '8901234567890',                       
    'Y',                                   
    'Y',                                   
    'Y',                                 
    'Y',                                  
    250.00,                                
    0.00,                                  
    50.00,                                
    '4000',                                
    '0',                                   
    100.00,                               
    '01WH',                                
    'SUP001',                             
    'SUP-SHOE-001',                        
    'Pair',                                
    1.00,                                  
    20.00,                                 
    5.00,                                  
    1200.00,                               
    '2025-08-01',                          
    'N',                                   
    10,                                    
    'TAX01',                               
    'TAX02',                               
    0.00,                                  
    'DISC01',                              
    'Y',                                   
    'Pair',                                
    1.00,                                 
    'N',                                   
    'GRP01',                               
    'N',                                   
    0.00,                                 
    'STD',                                
    1,                                     
    NULL,                                 
    'shoe1.jpg',                          
    'N',                                  
    0.00,                                  
    N'Breathable mesh running shoe',       
    NULL,                                 
    5.00,                                  
    0.00,                                  
    'C01',                                 
    'N',                                   
    0.00,                                 
    800.00,                               
    'INR',                                 
    '2025-07-15',                         
    'INR',                                
    1500.00,                               
    '01WH',                                
    'N',                                   
    'N',                                   
    'N',                                   
    12.00, 'CM',                          
    8.00, 'CM',                            
    30.00, 'CM',                           
    2880.00, 'CM3',                        
    0.80, 'KG',                            
    15.00, 'CM',                           
    10.00, 'CM',                          
    35.00, 'CM',                          
    5250.00, 'CM3',                        
    1.20, 'KG',                            
    'NIKE',                                
    '2025-08-10',                          
    '2025-08-01',                         
    '2025-08-22',                         
    'EXP01',                               
    1.00,                                
    'VAT18',                               
    1000.00,                               
    'Box',                                 
    'Pair',                                
    'Y',                                   
    '2025-01-01',                        
    '2026-01-01',                          
    'N',                                  
    '4',                                   
    'I',                                   
    'Pair',                                
    'IN',                                 
    250000.00,                             
    'M',                                   
    'Pair',                                
    'MRP',                                
    'B',                                   
    'Black',                               
    'Sports',                              
    'Adult',                               
    '42',                                  
    'SupplierX',                           
    'Retail',                             
    'Running Shoe',                        
    'STYLE001',                            
    'Nike',                                
    'Male',                               
    'ZoomX Runner',                        
    'Footwear',                           
    'Mesh',                               
    'Rubber',                             
    1500.00,                               
    'New arrival in 2025 collection',      
    '2025-08-22 14:30:00'                  
);

INSERT INTO OITM (
    ItemCode, ItemName, FrgnName, ItmsGrpCod, CstGrpCode, VatGourpSa, CodeBars,
    VATLiable, PrchseItem, SellItem, InvntItem, OnHand, IsCommited, OnOrder,
    IncomeAcct, ExmptIncom, MaxLevel, DfltWH, CardCode, SuppCatNum,
    BuyUnitMsr, NumInBuy, ReorderQty, MinLevel, LstEvlPric, LstEvlDate,
    CustomPer, Canceled, MnufctTime, WholSlsTax, RetilrTax, SpcialDisc,
    DscountCod, TrackSales, SalUnitMsr, NumInSale, Consig, QueryGroup, Counted,
    OpenBlnc, EvalSystem, UserSign, FREE, PicturName, Transfered, BlncTrnsfr,
    UserText, SerialNum, CommisPcnt, CommisSum, CommisGrp, TreeType, TreeQty,
    LastPurPrc, LastPurCur, LastPurDat, ExitCur, ExitPrice, ExitWH, AssetItem,
    WasCounted, ManSerNum, SHeight1, SHght1Unit, SWidth1, SWdth1Unit,
    SLength1, SLen1Unit, SVolume, SVolUnit, SWeight1, SWght1Unit,
    BHeight1, BHght1Unit, BWidth1, BWdth1Unit, BLength1, BLen1Unit,
    BVolume, BVolUnit, BWeight1, BWght1Unit, FirmCode, LstSalDate,
    CreateDate, UpdateDate, ExportCode, SalFactor1, PurFactor1,
    VatGroupPu, AvgPrice, PurPackMsr, SalPackMsr, validFor, validFrom, validTo,
    BlockOut, ObjType, ItemType, BaseUnit, CountryOrg, StockValue,
    IssueMthd, InvntryUom, PlaningSys, PrcrmntMtd,
    U_Colour, U_Category, U_SizeGrp, U_Size, U_Vendor, U_DisGrp, U_Product,
    U_StyleNo, U_Brand, U_Gender, U_ProdName, U_ProdType, U_Material, U_Sole,
    U_MRP, U_Remarks, U_UpdateTime
) VALUES (
    'SH002', N'Women Running Shoes', N'Schuhe Damen',
    101, 1, 'VAT18', '8901234567891',
    'Y', 'Y', 'Y', 'Y',
    180.00, 0.00, 40.00,
    '4000', '0', 80.00, '01WH', 'SUP002', 'SUP-SHOE-002',
    'Pair', 1.00, 15.00, 5.00, 1000.00, '2025-08-01',
    0.00, 'N', 8, 'TAX01', 'TAX02', 0.00,
    'DISC02', 'Y', 'Pair', 1.00, 'N', 'GRP01', 'N',
    0.00, 'STD', 1, NULL, 'shoe2.jpg', 'N', 0.00,
    N'Lightweight breathable women’s running shoe', NULL, 5.00, 0.00, 'C01', 'N', 0.00,
    700.00, 'INR', '2025-07-10', 'INR', 1300.00, '01WH', 'N',
    'N', 'N', 11.00, 'CM', 7.00, 'CM', 28.00, 'CM', 2156.00, 'CM3', 0.70, 'KG',
    14.00, 'CM', 9.00, 'CM', 33.00, 'CM', 4158.00, 'CM3', 1.10, 'KG',
    'ADIDAS', '2025-08-12', '2025-08-01', '2025-08-22', 'EXP02',
    1.00, 1.00, 'VAT18', 900.00, 'Box', 'Pair', 'Y',
    '2025-01-01', '2026-01-01', 'N', '4', 'I', 'Pair', 'IN', 200000.00,
    'M', 'Pair', 'MRP', 'B',
    'Pink', 'Sports', 'Adult', '38', 'SupplierY', 'Retail',
    'Running Shoe', 'STYLE002', 'Adidas', 'Female', 'Ultraboost Light',
    'Footwear', 'Knit', 'Rubber', 1300.00,
    'Popular in women’s sportswear 2025', '2025-08-22 14:45:00'
);

INSERT INTO OITM (
    ItemCode, ItemName, FrgnName, ItmsGrpCod, CstGrpCode, VatGourpSa, CodeBars,
    VATLiable, PrchseItem, SellItem, InvntItem, OnHand, IsCommited, OnOrder,
    IncomeAcct, ExmptIncom, MaxLevel, DfltWH, CardCode, SuppCatNum,
    BuyUnitMsr, NumInBuy, ReorderQty, MinLevel, LstEvlPric, LstEvlDate,
    CustomPer, Canceled, MnufctTime, WholSlsTax, RetilrTax, SpcialDisc,
    DscountCod, TrackSales, SalUnitMsr, NumInSale, Consig, QueryGroup, Counted,
    OpenBlnc, EvalSystem, UserSign, FREE, PicturName, Transfered, BlncTrnsfr,
    UserText, SerialNum, CommisPcnt, CommisSum, CommisGrp, TreeType, TreeQty,
    LastPurPrc, LastPurCur, LastPurDat, ExitCur, ExitPrice, ExitWH, AssetItem,
    WasCounted, ManSerNum, SHeight1, SHght1Unit, SWidth1, SWdth1Unit,
    SLength1, SLen1Unit, SVolume, SVolUnit, SWeight1, SWght1Unit,
    BHeight1, BHght1Unit, BWidth1, BWdth1Unit, BLength1, BLen1Unit,
    BVolume, BVolUnit, BWeight1, BWght1Unit, FirmCode, LstSalDate,
    CreateDate, UpdateDate, ExportCode, SalFactor1, PurFactor1,
    VatGroupPu, AvgPrice, PurPackMsr, SalPackMsr, validFor, validFrom, validTo,
    BlockOut, ObjType, ItemType, BaseUnit, CountryOrg, StockValue,
    IssueMthd, InvntryUom, PlaningSys, PrcrmntMtd,
    U_Colour, U_Category, U_SizeGrp, U_Size, U_Vendor, U_DisGrp, U_Product,
    U_StyleNo, U_Brand, U_Gender, U_ProdName, U_ProdType, U_Material, U_Sole,
    U_MRP, U_Remarks, U_UpdateTime
) VALUES (
    'SH003', N'Kids School Shoes', N'Kinderschuhe',
    102, 1, 'VAT12', '8901234567892',
    'Y', 'Y', 'Y', 'Y',
    300.00, 0.00, 60.00,
    '4000', '0', 120.00, '02WH', 'SUP003', 'SUP-SHOE-003',
    'Pair', 1.00, 25.00, 10.00, 600.00, '2025-08-01',
    0.00, 'N', 7, 'TAX01', 'TAX02', 0.00,
    'DISC03', 'Y', 'Pair', 1.00, 'N', 'GRP02', 'N',
    0.00, 'STD', 1, NULL, 'shoe3.jpg', 'N', 0.00,
    N'Durable leather school shoes for kids', NULL, 4.00, 0.00, 'C02', 'N', 0.00,
    450.00, 'INR', '2025-07-05', 'INR', 800.00, '02WH', 'N',
    'N', 'N', 9.00, 'CM', 6.00, 'CM', 24.00, 'CM', 1296.00, 'CM3', 0.50, 'KG',
    12.00, 'CM', 8.00, 'CM', 28.00, 'CM', 2688.00, 'CM3', 0.80, 'KG',
    'BATA', '2025-08-11', '2025-08-01', '2025-08-22', 'EXP03',
    1.00, 1.00, 'VAT12', 550.00, 'Box', 'Pair', 'Y',
    '2025-01-01', '2026-01-01', 'N', '4', 'I', 'Pair', 'IN', 240000.00,
    'M', 'Pair', 'MRP', 'B',
    'Black', 'School', 'Kids', '2', 'SupplierZ', 'Retail',
    'School Shoe', 'STYLE003', 'Bata', 'Unisex', 'Classic School Shoe',
    'Footwear', 'Leather', 'Rubber', 800.00,
    'Back-to-school season special', '2025-08-22 15:00:00'
);

INSERT INTO OITM (
    ItemCode, ItemName, FrgnName, ItmsGrpCod, CstGrpCode, VatGourpSa, CodeBars,
    VATLiable, PrchseItem, SellItem, InvntItem, OnHand, IsCommited, OnOrder,
    IncomeAcct, ExmptIncom, MaxLevel, DfltWH, CardCode, SuppCatNum,
    BuyUnitMsr, NumInBuy, ReorderQty, MinLevel, LstEvlPric, LstEvlDate,
    CustomPer, Canceled, MnufctTime, WholSlsTax, RetilrTax, SpcialDisc,
    DscountCod, TrackSales, SalUnitMsr, NumInSale, Consig, QueryGroup, Counted,
    OpenBlnc, EvalSystem, UserSign, FREE, PicturName, Transfered, BlncTrnsfr,
    UserText, SerialNum, CommisPcnt, CommisSum, CommisGrp, TreeType, TreeQty,
    LastPurPrc, LastPurCur, LastPurDat, ExitCur, ExitPrice, ExitWH, AssetItem,
    WasCounted, ManSerNum, SHeight1, SHght1Unit, SWidth1, SWdth1Unit,
    SLength1, SLen1Unit, SVolume, SVolUnit, SWeight1, SWght1Unit,
    BHeight1, BHght1Unit, BWidth1, BWdth1Unit, BLength1, BLen1Unit,
    BVolume, BVolUnit, BWeight1, BWght1Unit, FirmCode, LstSalDate,
    CreateDate, UpdateDate, ExportCode, SalFactor1, PurFactor1,
    VatGroupPu, AvgPrice, PurPackMsr, SalPackMsr, validFor, validFrom, validTo,
    BlockOut, ObjType, ItemType, BaseUnit, CountryOrg, StockValue,
    IssueMthd, InvntryUom, PlaningSys, PrcrmntMtd,
    U_Colour, U_Category, U_SizeGrp, U_Size, U_Vendor, U_DisGrp, U_Product,
    U_StyleNo, U_Brand, U_Gender, U_ProdName, U_ProdType, U_Material, U_Sole,
    U_MRP, U_Remarks, U_UpdateTime
) VALUES (
    'SH004', N'Men Formal Shoes', N'Herrenschuhe',
    103, 1, 'VAT18', '8901234567893',
    'Y', 'Y', 'Y', 'Y',
    120.00, 0.00, 30.00,
    '4000', '0', 90.00, '03WH', 'SUP004', 'SUP-SHOE-004',
    'Pair', 1.00, 12.00, 4.00, 1500.00, '2025-08-01',
    0.00, 'N', 12, 'TAX01', 'TAX02', 0.00,
    'DISC04', 'Y', 'Pair', 1.00, 'N', 'GRP03', 'N',
    0.00, 'STD', 1, NULL, 'shoe4.jpg', 'N', 0.00,
    N'Classic men’s leather formal office shoe', NULL, 6.00, 0.00, 'C03', 'N', 0.00,
    1100.00, 'INR', '2025-07-20', 'INR', 2000.00, '03WH', 'N',
    'N', 'N', 13.00, 'CM', 8.00, 'CM', 32.00, 'CM', 3328.00, 'CM3', 1.20, 'KG',
    16.00, 'CM', 10.00, 'CM', 36.00, 'CM', 5760.00, 'CM3', 1.60, 'KG',
    'CLARKS', '2025-08-14', '2025-08-01', '2025-08-22', 'EXP04',
    1.00, 1.00, 'VAT18', 1400.00, 'Box', 'Pair', 'Y',
    '2025-01-01', '2026-01-01', 'N', '4', 'I', 'Pair', 'IN', 150000.00,
    'M', 'Pair', 'MRP', 'B',
    'Brown', 'Formal', 'Adult', '44', 'SupplierW', 'Retail',
    'Formal Shoe', 'STYLE004', 'Clarks', 'Male', 'Executive Leather Shoe',
    'Footwear', 'Leather', 'Leather', 2000.00,
    'Premium leather shoes for executives', '2025-08-22 15:15:00'
);

select * from OITM;
 
DELETE FROM OITM
WHERE ItemCode IN ('SHOE001', 'SHOE002', 'SHOE003');


INSERT INTO OITM (
    ItemCode, ItemName, FrgnName, ItmsGrpCod, CstGrpCode, VatGourpSa, CodeBars,
    VATLiable, PrchseItem, SellItem, InvntItem, OnHand, IsCommited, OnOrder,
    IncomeAcct, ExmptIncom, MaxLevel, DfltWH, CardCode, SuppCatNum,
    BuyUnitMsr, NumInBuy, ReorderQty, MinLevel, LstEvlPric, LstEvlDate,
    CustomPer, Canceled, MnufctTime, WholSlsTax, RetilrTax, SpcialDisc,
    DscountCod, TrackSales, SalUnitMsr, NumInSale, Consig, QueryGroup, Counted,
    OpenBlnc, EvalSystem, UserSign, FREE, PicturName, Transfered, BlncTrnsfr,
    UserText, SerialNum, CommisPcnt, CommisSum, CommisGrp, TreeType, TreeQty,
    LastPurPrc, LastPurCur, LastPurDat, ExitCur, ExitPrice, ExitWH, AssetItem,
    WasCounted, ManSerNum, SHeight1, SHght1Unit, SWidth1, SWdth1Unit,
    SLength1, SLen1Unit, SVolume, SVolUnit, SWeight1, SWght1Unit,
    BHeight1, BHght1Unit, BWidth1, BWdth1Unit, BLength1, BLen1Unit,
    BVolume, BVolUnit, BWeight1, BWght1Unit, FirmCode, LstSalDate,
    CreateDate, UpdateDate, ExportCode, SalFactor1, PurFactor1,
    VatGroupPu, AvgPrice, PurPackMsr, SalPackMsr, validFor, validFrom, validTo,
    BlockOut, ObjType, ItemType, BaseUnit, CountryOrg, StockValue,
    IssueMthd, InvntryUom, PlaningSys, PrcrmntMtd,
    U_Colour, U_Category, U_SizeGrp, U_Size, U_Vendor, U_DisGrp, U_Product,
    U_StyleNo, U_Brand, U_Gender, U_ProdName, U_ProdType, U_Material, U_Sole,
    U_MRP, U_Remarks, U_UpdateTime
) VALUES (
    'SH001', N'Men Sports Shoes', N'Schuhe Herren',
    100, 1, 'VAT18', '8901234567890',
    'Y', 'Y', 'Y', 'Y',
    150.00, 0.00, 50.00,
    '4000', '0', 100.00, '01WH', 'SUP001', 'SUP-SHOE-001',
    'Pair', 1.00, 10.00, 5.00, 1200.00, '2025-08-01',
    0.00, 'N', 10, 'TAX01', 'TAX02', 0.00,
    'DISC01', 'Y', 'Pair', 1.00, 'N', 'GRP01', 'N',
    0.00, 'STD', 1, 'N/A', 'shoe1.jpg', 'N', 0.00,
    N'Men’s breathable mesh sports shoe', 'N/A', 5.00, 0.00, 'C01', 'N', 0.00,
    800.00, 'INR', '2025-07-15', 'INR', 1500.00, '01WH', 'N',
    'N', 'N', 10.00, 'CM', 8.00, 'CM', 30.00, 'CM', 2400.00, 'CM3', 0.80, 'KG',
    15.00, 'CM', 10.00, 'CM', 35.00, 'CM', 5250.00, 'CM3', 1.20, 'KG',
    'NIKE', '2025-08-10', '2025-08-01', '2025-08-22', 'EXP01',
    1.00, 1.00, 'VAT18', 1000.00, 'Box', 'Pair', 'Y',
    '2025-01-01', '2026-01-01', 'N', '4', 'I', 'Pair', 'IN', 180000.00,
    'M', 'Pair', 'MRP', 'B',
    'Blue', 'Sports', 'Adult', '42', 'SupplierX', 'Retail',
    'Running Shoe', 'STYLE001', 'Nike', 'Male', 'Air Zoom Pegasus',
    'Footwear', 'Mesh', 'Rubber', 1500.00,
    'Best-selling sports shoe in India 2025', '2025-08-22 14:30:00'
);

INSERT INTO OITM (
    ItemCode, ItemName, FrgnName, ItmsGrpCod, CstGrpCode, VatGourpSa, CodeBars,
    VATLiable, PrchseItem, SellItem, InvntItem, OnHand, IsCommited, OnOrder,
    IncomeAcct, ExmptIncom, MaxLevel, DfltWH, CardCode, SuppCatNum,
    BuyUnitMsr, NumInBuy, ReorderQty, MinLevel, LstEvlPric, LstEvlDate,
    CustomPer, Canceled, MnufctTime, WholSlsTax, RetilrTax, SpcialDisc,
    DscountCod, TrackSales, SalUnitMsr, NumInSale, Consig, QueryGroup, Counted,
    OpenBlnc, EvalSystem, UserSign, FREE, PicturName, Transfered, BlncTrnsfr,
    UserText, SerialNum, CommisPcnt, CommisSum, CommisGrp, TreeType, TreeQty,
    LastPurPrc, LastPurCur, LastPurDat, ExitCur, ExitPrice, ExitWH, AssetItem,
    WasCounted, ManSerNum, SHeight1, SHght1Unit, SWidth1, SWdth1Unit,
    SLength1, SLen1Unit, SVolume, SVolUnit, SWeight1, SWght1Unit,
    BHeight1, BHght1Unit, BWidth1, BWdth1Unit, BLength1, BLen1Unit,
    BVolume, BVolUnit, BWeight1, BWght1Unit, FirmCode, LstSalDate,
    CreateDate, UpdateDate, ExportCode, SalFactor1, PurFactor1,
    VatGroupPu, AvgPrice, PurPackMsr, SalPackMsr, validFor, validFrom, validTo,
    BlockOut, ObjType, ItemType, BaseUnit, CountryOrg, StockValue,
    IssueMthd, InvntryUom, PlaningSys, PrcrmntMtd,
    U_Colour, U_Category, U_SizeGrp, U_Size, U_Vendor, U_DisGrp, U_Product,
    U_StyleNo, U_Brand, U_Gender, U_ProdName, U_ProdType, U_Material, U_Sole,
    U_MRP, U_Remarks, U_UpdateTime
) VALUES (
    'SH002', N'Women Running Shoes', N'Schuhe Damen',
    101, 1, 'VAT18', '8901234567891',
    'Y', 'Y', 'Y', 'Y',
    180.00, 0.00, 40.00,
    '4000', '0', 80.00, '01WH', 'SUP002', 'SUP-SHOE-002',
    'Pair', 1.00, 15.00, 5.00, 1000.00, '2025-08-01',
    0.00, 'N', 8, 'TAX01', 'TAX02', 0.00,
    'DISC02', 'Y', 'Pair', 1.00, 'N', 'GRP01', 'N',
    0.00, 'STD', 1, 'N/A', 'shoe2.jpg', 'N', 0.00,
    N'Lightweight breathable women’s running shoe', 'N/A', 5.00, 0.00, 'C01', 'N', 0.00,
    700.00, 'INR', '2025-07-10', 'INR', 1300.00, '01WH', 'N',
    'N', 'N', 11.00, 'CM', 7.00, 'CM', 28.00, 'CM', 2156.00, 'CM3', 0.70, 'KG',
    14.00, 'CM', 9.00, 'CM', 33.00, 'CM', 4158.00, 'CM3', 1.10, 'KG',
    'ADIDAS', '2025-08-12', '2025-08-01', '2025-08-22', 'EXP02',
    1.00, 1.00, 'VAT18', 900.00, 'Box', 'Pair', 'Y',
    '2025-01-01', '2026-01-01', 'N', '4', 'I', 'Pair', 'IN', 200000.00,
    'M', 'Pair', 'MRP', 'B',
    'Pink', 'Sports', 'Adult', '38', 'SupplierY', 'Retail',
    'Running Shoe', 'STYLE002', 'Adidas', 'Female', 'Ultraboost Light',
    'Footwear', 'Knit', 'Rubber', 1300.00,
    'Popular in women’s sportswear 2025', '2025-08-22 14:45:00'
);


INSERT INTO OITM (
ItemCode, ItemName, FrgnName, ItmsGrpCod, CstGrpCode, VatGourpSa, CodeBars,
    VATLiable, PrchseItem, SellItem, InvntItem, OnHand, IsCommited, OnOrder,
    IncomeAcct, ExmptIncom, MaxLevel, DfltWH, CardCode, SuppCatNum,
    BuyUnitMsr, NumInBuy, ReorderQty, MinLevel, LstEvlPric, LstEvlDate,
    CustomPer, Canceled, MnufctTime, WholSlsTax, RetilrTax, SpcialDisc,
    DscountCod, TrackSales, SalUnitMsr, NumInSale, Consig, QueryGroup, Counted,
    OpenBlnc, EvalSystem, UserSign, FREE, PicturName, Transfered, BlncTrnsfr,
    UserText, SerialNum, CommisPcnt, CommisSum, CommisGrp, TreeType, TreeQty,
    LastPurPrc, LastPurCur, LastPurDat, ExitCur, ExitPrice, ExitWH, AssetItem,
    WasCounted, ManSerNum, SHeight1, SHght1Unit, SWidth1, SWdth1Unit,
    SLength1, SLen1Unit, SVolume, SVolUnit, SWeight1, SWght1Unit,
    BHeight1, BHght1Unit, BWidth1, BWdth1Unit, BLength1, BLen1Unit,
    BVolume, BVolUnit, BWeight1, BWght1Unit, FirmCode, LstSalDate,
    CreateDate, UpdateDate, ExportCode, SalFactor1, PurFactor1,
    VatGroupPu, AvgPrice, PurPackMsr, SalPackMsr, validFor, validFrom, validTo,
    BlockOut, ObjType, ItemType, BaseUnit, CountryOrg, StockValue,
    IssueMthd, InvntryUom, PlaningSys, PrcrmntMtd,
    U_Colour, U_Category, U_SizeGrp, U_Size, U_Vendor, U_DisGrp, U_Product,
    U_StyleNo, U_Brand, U_Gender, U_ProdName, U_ProdType, U_Material, U_Sole,
    U_MRP, U_Remarks, U_UpdateTime
 ) VALUES (
    'SH003', N'Kids School Shoes', N'Kinderschuhe',
    102, 1, 'VAT12', '8901234567892',
    'Y', 'Y', 'Y', 'Y',
    300.00, 0.00, 60.00,
    '4000', '0', 120.00, '02WH', 'SUP003', 'SUP-SHOE-003',
    'Pair', 1.00, 25.00, 10.00, 600.00, '2025-08-01',
    0.00, 'N', 7, 'TAX01', 'TAX02', 0.00,
    'DISC03', 'Y', 'Pair', 1.00, 'N', 'GRP02', 'N',
    0.00, 'STD', 1, 'N/A', 'shoe3.jpg', 'N', 0.00,
    N'Durable leather school shoes for kids', 'N/A', 4.00, 0.00, 'C02', 'N', 0.00,
    450.00, 'INR', '2025-07-05', 'INR', 800.00, '02WH', 'N',
    'N', 'N', 9.00, 'CM', 6.00, 'CM', 24.00, 'CM', 1296.00, 'CM3', 0.50, 'KG',
    12.00, 'CM', 8.00, 'CM', 28.00, 'CM', 2688.00, 'CM3', 0.80, 'KG',
    'BATA', '2025-08-11', '2025-08-01', '2025-08-22', 'EXP03',
    1.00, 1.00, 'VAT12', 550.00, 'Box', 'Pair', 'Y',
    '2025-01-01', '2026-01-01', 'N', '4', 'I', 'Pair', 'IN', 240000.00,
    'M', 'Pair', 'MRP', 'B',
    'Black', 'School', 'Kids', '2', 'SupplierZ', 'Retail',
    'School Shoe', 'STYLE003', 'Bata', 'Unisex', 'Classic School Shoe',
    'Footwear', 'Leather', 'Rubber', 800.00,
    'Back-to-school season special', '2025-08-22 15:00:00'
);


INSERT INTO OITM (
ItemCode, ItemName, FrgnName, ItmsGrpCod, CstGrpCode, VatGourpSa, CodeBars,
    VATLiable, PrchseItem, SellItem, InvntItem, OnHand, IsCommited, OnOrder,
    IncomeAcct, ExmptIncom, MaxLevel, DfltWH, CardCode, SuppCatNum,
    BuyUnitMsr, NumInBuy, ReorderQty, MinLevel, LstEvlPric, LstEvlDate,
    CustomPer, Canceled, MnufctTime, WholSlsTax, RetilrTax, SpcialDisc,
    DscountCod, TrackSales, SalUnitMsr, NumInSale, Consig, QueryGroup, Counted,
    OpenBlnc, EvalSystem, UserSign, FREE, PicturName, Transfered, BlncTrnsfr,
    UserText, SerialNum, CommisPcnt, CommisSum, CommisGrp, TreeType, TreeQty,
    LastPurPrc, LastPurCur, LastPurDat, ExitCur, ExitPrice, ExitWH, AssetItem,
    WasCounted, ManSerNum, SHeight1, SHght1Unit, SWidth1, SWdth1Unit,
    SLength1, SLen1Unit, SVolume, SVolUnit, SWeight1, SWght1Unit,
    BHeight1, BHght1Unit, BWidth1, BWdth1Unit, BLength1, BLen1Unit,
    BVolume, BVolUnit, BWeight1, BWght1Unit, FirmCode, LstSalDate,
    CreateDate, UpdateDate, ExportCode, SalFactor1, PurFactor1,
    VatGroupPu, AvgPrice, PurPackMsr, SalPackMsr, validFor, validFrom, validTo,
    BlockOut, ObjType, ItemType, BaseUnit, CountryOrg, StockValue,
    IssueMthd, InvntryUom, PlaningSys, PrcrmntMtd,
    U_Colour, U_Category, U_SizeGrp, U_Size, U_Vendor, U_DisGrp, U_Product,
    U_StyleNo, U_Brand, U_Gender, U_ProdName, U_ProdType, U_Material, U_Sole,
    U_MRP, U_Remarks, U_UpdateTime
) VALUES (
    'SH004', N'Men Formal Shoes', N'Herrenschuhe',
    103, 1, 'VAT18', '8901234567893',
    'Y', 'Y', 'Y', 'Y',
    120.00, 0.00, 30.00,
    '4000', '0', 90.00, '03WH', 'SUP004', 'SUP-SHOE-004',
    'Pair', 1.00, 12.00, 4.00, 1500.00, '2025-08-01',
    0.00, 'N', 12, 'TAX01', 'TAX02', 0.00,
    'DISC04', 'Y', 'Pair', 1.00, 'N', 'GRP03', 'N',
    0.00, 'STD', 1, 'N/A', 'shoe4.jpg', 'N', 0.00,
    N'Classic men’s leather formal office shoe', 'N/A', 6.00, 0.00, 'C03', 'N', 0.00,
    1100.00, 'INR', '2025-07-20', 'INR', 2000.00, '03WH', 'N',
    'N', 'N', 13.00, 'CM', 8.00, 'CM', 32.00, 'CM', 3328.00, 'CM3', 1.20, 'KG',
    16.00, 'CM', 10.00, 'CM', 36.00, 'CM', 5760.00, 'CM3', 1.60, 'KG',
    'CLARKS', '2025-08-14', '2025-08-01', '2025-08-22', 'EXP04',
    1.00, 1.00, 'VAT18', 1400.00, 'Box', 'Pair', 'Y',
    '2025-01-01', '2026-01-01', 'N', '4', 'I', 'Pair', 'IN', 150000.00,
    'M', 'Pair', 'MRP', 'B',
    'Brown', 'Formal', 'Adult', '44', 'SupplierW', 'Retail',
    'Formal Shoe', 'STYLE004', 'Clarks', 'Male', 'Executive Leather Shoe',
    'Footwear', 'Leather', 'Leather', 2000.00,
    'Premium leather shoes for executives', '2025-08-22 15:15:00'
);

select *from OITM;
UPDATE OITM
SET 
    U_Height = 12.5,
    U_HType = 'CM',
    U_Length = 30.0,
    U_LType = 'CM',
    U_Width = 9.5,
    U_WType = 'CM',
    U_ShipCost = 250.00,
    U_Weight = 0.80,
    U_Exchange = 'Y',
    U_TryBuy = 'N',
    U_TryBuyAmt = 0.00,
    U_ChartID = 'CHART01',
    U_SpetItem = 'Running Shoe',       -- ✅ correct column spelling
    U_OnLineCat = 'Sportswear',
    U_conceptho = 'High-performance lightweight cushioned running shoe' -- ✅ correct spelling
WHERE U_ProdName = 'ZoomX Runner';

WITH CTE AS (
    SELECT *,
           ROW_NUMBER() OVER (PARTITION BY ItemCode ORDER BY ItemCode) AS rn
    FROM OITM
)
DELETE FROM CTE WHERE rn > 1;

select *from OITM;
SELECT COLUMN_NAME
FROM INFORMATION_SCHEMA.COLUMNS
WHERE TABLE_NAME = 'OITM';


